spring:
  application:
    name: 'location-service'
  datasource:
    url: 'jdbc:h2:mem:location_db'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
