eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${eureka_default_zone}
server:
  port: ${server_port}
spring:
  application:
    name: ${application_name}
  cloud:
    config:
      server:
        git:
          uri: ${config_server_git_uri}
        default-label: ${config_server_default_branch}
